services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - volume_formative_config:/usr/share/nginx/html/config
      - volume_formative_images:/usr/share/nginx/html/images
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=formative
      - DATABASE_USER=formative
      - DATABASE_PASSWORD=ch4ng3m3!
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
  database:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=formative
      - POSTGRES_PASSWORD=ch4ng3m3!
      - POSTGRES_DB=formative
    volumes:
      - volume_formative_database:/var/lib/postgresql/data
volumes:
  volume_formative_config:
  volume_formative_images:
  volume_formative_database: