name: Build and Release Frontend

on:
  push:
    tags:
      - '*.*.*'

permissions:
  actions: write
  contents: write

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS 21.7.1
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.1
      - name: Install dependencies
        run: npm install

      - name: Build NodeJS
        run: npm run build

      - name: Zip 'dist' Artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: frontend/dist
          dest: dist.zip

      - name: Upload 'dist' Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist.zip
          path: dist.zip

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Create Release ${{ github.ref }}
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Download 'dist' artifact
        uses: actions/download-artifact@v4
        with:
          name: dist.zip

      - name: Attach the Artifact to the Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: dist-${{ github.ref_name }}.zip
          asset_content_type: application/zip