name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS {{{ env.node-version }}}
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.1
      - name: Install dependencies
        run: npm install
      - name: Build NodeJS
        run: npm run build

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Zip 'dist' Artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/
          dest: dist.zip

      - name: Upload 'dist' Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: dist.zip
          path: dist.zip